#!/usr/bin/env python3
"""Run the attribute classifier bake-off and log results to MLflow.

Usage:
    python run_attribute_bakeoff.py --manifest data/eval/attribute/manifest.json \
        --candidate resnet18 \
        --onnx-path artifacts/models/attribute/resnet18.onnx \
        --triton-url localhost:8001 \
        --mlflow-uri http://localhost:5000
"""

from __future__ import annotations

import argparse
import importlib
import json
import statistics
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


COLOR_NAMES: tuple[str, ...] = (
    "red",
    "blue",
    "white",
    "black",
    "silver",
    "green",
    "yellow",
    "brown",
    "orange",
    "unknown",
)
SAFE_DEFAULT_ATTRIBUTE = "resnet18"
DEFAULT_EXPERIMENT = "attribute-bakeoff"
DEFAULT_BATCH_SIZE = 32
COLOR_TO_INDEX = {color_name: index for index, color_name in enumerate(COLOR_NAMES)}


@dataclass(frozen=True)
class AttributeCandidate:
    name: str
    onnx_path: Path
    triton_model_name: str
    input_name: str = "images"
    output_name: str = "probabilities"
    input_size: int = 224
    is_safe_default: bool = False


@dataclass(frozen=True)
class DatasetMetadata:
    manifest_path: Path
    export_timestamp: str | None
    source_project: str
    total_crops: int
    per_color_counts: dict[str, int]


@dataclass(frozen=True)
class CropRecord:
    crop_path: Path
    color_name: str
    object_class: str
    attribute_name: str
    source_image: str


@dataclass(frozen=True)
class LatencyStats:
    p50_ms: float
    p95_ms: float
    p99_ms: float


@dataclass(frozen=True)
class AttributeMetrics:
    overall_accuracy: float
    macro_per_color_accuracy: float
    unknown_rate: float
    latency_p50_ms: float
    latency_p95_ms: float
    latency_p99_ms: float
    throughput_fps: float
    evaluated_crops: int
    batch_size: int
    per_color_accuracy: dict[str, float]
    confusion_matrix: list[list[int]]
    confusion_black_blue: float
    confusion_white_silver: float
    confusion_brown_orange: float


DEFAULT_CANDIDATES: dict[str, AttributeCandidate] = {
    "resnet18": AttributeCandidate(
        name="resnet18",
        onnx_path=Path("artifacts/models/attribute/resnet18.onnx"),
        triton_model_name="color_classifier",
        is_safe_default=True,
    ),
    "efficientnet_b0": AttributeCandidate(
        name="efficientnet_b0",
        onnx_path=Path("artifacts/models/attribute/efficientnet_b0.onnx"),
        triton_model_name="color_classifier",
    ),
}


class ClassifierBackend(Protocol):
    def infer_batch(self, batch: Any) -> Any:
        ...


def require_module(module_name: str, install_hint: str) -> Any:
    try:
        return importlib.import_module(module_name)
    except ImportError as exc:  # pragma: no cover - depends on local env
        raise RuntimeError(
            f"missing optional dependency '{module_name}'; install {install_hint}"
        ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/eval/attribute/manifest.json"),
        help="Manifest generated by prepare_color_eval_data.py.",
    )
    parser.add_argument(
        "--candidate",
        required=True,
        choices=sorted(DEFAULT_CANDIDATES),
        help="Attribute classifier candidate to evaluate.",
    )
    parser.add_argument(
        "--onnx-path",
        type=Path,
        help="Override the default ONNX path for the selected candidate.",
    )
    parser.add_argument(
        "--triton-url",
        default="127.0.0.1:8001",
        help="Triton gRPC endpoint, for example 127.0.0.1:8001.",
    )
    parser.add_argument(
        "--triton-model",
        help="Override the Triton model name. Defaults to color_classifier.",
    )
    parser.add_argument(
        "--mlflow-uri",
        default="http://127.0.0.1:5000",
        help="MLflow tracking URI.",
    )
    parser.add_argument(
        "--mlflow-experiment",
        default=DEFAULT_EXPERIMENT,
        help="MLflow experiment name.",
    )
    parser.add_argument(
        "--confidence-threshold",
        type=float,
        default=0.30,
        help="Confidence threshold below which predictions fall back to unknown.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help="Evaluation batch size. Defaults to the Triton attribute envelope of 32.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("artifacts/bakeoff/attribute"),
        help="Directory for local run artifacts before they are logged to MLflow.",
    )
    return parser.parse_args()


def resolve_candidate(args: argparse.Namespace) -> AttributeCandidate:
    base = DEFAULT_CANDIDATES[args.candidate]
    return AttributeCandidate(
        name=base.name,
        onnx_path=args.onnx_path or base.onnx_path,
        triton_model_name=args.triton_model or base.triton_model_name,
        input_name=base.input_name,
        output_name=base.output_name,
        input_size=base.input_size,
        is_safe_default=base.is_safe_default,
    )


def detect_git_state() -> tuple[str | None, bool | None]:
    try:
        revision = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        dirty = bool(
            subprocess.run(
                ["git", "status", "--porcelain"],
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None, None
    return revision or None, dirty


def load_manifest(manifest_path: Path) -> tuple[list[CropRecord], DatasetMetadata]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"evaluation manifest not found: {manifest_path}")
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    colors = tuple(str(value) for value in payload.get("colors", ()))
    if colors != COLOR_NAMES:
        raise RuntimeError(
            "manifest colors must match the canonical 10-color vocabulary in order"
        )

    per_color_counts = {
        color_name: int(payload.get("per_color_counts", {}).get(color_name, 0))
        for color_name in COLOR_NAMES
    }
    missing_colors = [color for color, count in per_color_counts.items() if count <= 0]
    if missing_colors:
        raise RuntimeError(
            "evaluation manifest is incomplete; missing crops for colors: "
            + ", ".join(missing_colors)
        )

    items = payload.get("items")
    if not isinstance(items, list) or not items:
        raise RuntimeError("evaluation manifest contains no crop items")

    records: list[CropRecord] = []
    for item in items:
        raw_path = item.get("crop_path")
        color_name = str(item.get("color", "")).strip().lower()
        if not raw_path:
            raise RuntimeError("manifest crop item is missing crop_path")
        if color_name not in COLOR_NAMES:
            raise RuntimeError(f"manifest crop item has invalid color label: {color_name!r}")
        crop_path = Path(raw_path)
        if not crop_path.is_absolute():
            crop_path = (manifest_path.parent / crop_path).resolve()
        if not crop_path.exists():
            raise FileNotFoundError(f"crop referenced by manifest does not exist: {crop_path}")
        records.append(
            CropRecord(
                crop_path=crop_path,
                color_name=color_name,
                object_class=str(item.get("object_class", "")),
                attribute_name=str(item.get("attribute_name", "")),
                source_image=str(item.get("source_image", "")),
            )
        )

    total_crops = int(payload.get("total_crops", 0))
    if total_crops != len(records):
        raise RuntimeError(
            "manifest total_crops does not match the number of crop items "
            f"({total_crops} != {len(records)})"
        )

    metadata = DatasetMetadata(
        manifest_path=manifest_path,
        export_timestamp=str(payload.get("export_timestamp"))
        if payload.get("export_timestamp") is not None
        else None,
        source_project=str(payload.get("source_project", "unknown")),
        total_crops=total_crops,
        per_color_counts=per_color_counts,
    )
    return records, metadata


def load_batch_tensors(records: list[CropRecord], input_size: int) -> Any:
    image_module = require_module("PIL.Image", "Pillow")
    numpy = require_module("numpy", "numpy")
    tensors: list[Any] = []
    for record in records:
        with image_module.open(record.crop_path) as image:
            resized = image.convert("RGB").resize(
                (input_size, input_size),
                image_module.BILINEAR,
            )
            tensor = numpy.asarray(resized, dtype=numpy.float32) / 255.0
            if tensor.ndim != 3 or tensor.shape[2] != 3:
                raise RuntimeError(f"unexpected crop shape for {record.crop_path}")
            tensors.append(tensor.transpose(2, 0, 1))
    return numpy.stack(tensors, axis=0)


class TritonClassifierBackend:
    def __init__(self, url: str, model_name: str, input_name: str, output_name: str) -> None:
        grpcclient = require_module("tritonclient.grpc", "tritonclient[grpc]")
        self._grpcclient = grpcclient
        self._client = grpcclient.InferenceServerClient(url=url)
        self._model_name = model_name
        self._input_name = input_name
        self._output_name = output_name
        self._verify_ready(url)

    def _verify_ready(self, url: str) -> None:
        try:
            if not self._client.is_server_live():
                raise RuntimeError(f"Triton server at {url} is not live")
            if not self._client.is_model_ready(self._model_name):
                raise RuntimeError(f"Triton model {self._model_name!r} is not ready")
        except Exception as exc:  # pragma: no cover - depends on external service
            raise RuntimeError(f"unable to use Triton backend at {url}: {exc}") from exc

    def infer_batch(self, batch: Any) -> Any:
        inputs = [
            self._grpcclient.InferInput(
                self._input_name,
                list(batch.shape),
                "FP32",
            )
        ]
        inputs[0].set_data_from_numpy(batch)
        outputs = [self._grpcclient.InferRequestedOutput(self._output_name)]
        try:
            result = self._client.infer(
                model_name=self._model_name,
                inputs=inputs,
                outputs=outputs,
            )
        except Exception as exc:  # pragma: no cover - depends on external service
            raise RuntimeError(f"Triton inference failed: {exc}") from exc
        output = result.as_numpy(self._output_name)
        if output is None:
            raise RuntimeError(
                f"Triton output {self._output_name!r} was not returned for {self._model_name!r}"
            )
        return output


class OnnxRuntimeClassifierBackend:
    def __init__(self, onnx_path: Path, input_name: str, output_name: str) -> None:
        if not onnx_path.exists():
            raise FileNotFoundError(f"ONNX model not found: {onnx_path}")
        onnxruntime = require_module("onnxruntime", "onnxruntime")
        self._session = onnxruntime.InferenceSession(
            str(onnx_path),
            providers=["CPUExecutionProvider"],
        )
        self._input_name = input_name
        self._output_name = output_name

    def infer_batch(self, batch: Any) -> Any:
        outputs = self._session.run([self._output_name], {self._input_name: batch})
        if not outputs:
            raise RuntimeError(f"ONNX runtime returned no outputs for {self._output_name!r}")
        return outputs[0]


def select_backend(
    candidate: AttributeCandidate,
    triton_url: str,
) -> tuple[str, ClassifierBackend]:
    triton_error: str | None = None
    if triton_url.strip():
        try:
            return (
                "triton",
                TritonClassifierBackend(
                    triton_url.strip(),
                    candidate.triton_model_name,
                    candidate.input_name,
                    candidate.output_name,
                ),
            )
        except Exception as exc:
            triton_error = str(exc)

    try:
        return (
            "onnxruntime",
            OnnxRuntimeClassifierBackend(
                candidate.onnx_path,
                candidate.input_name,
                candidate.output_name,
            ),
        )
    except Exception as exc:
        if triton_error is not None:
            raise RuntimeError(
                "no usable inference backend found; Triton error: "
                f"{triton_error}; ONNX Runtime error: {exc}"
            ) from exc
        raise


def softmax_rows(values: Any) -> Any:
    numpy = require_module("numpy", "numpy")
    shifted = values - numpy.max(values, axis=1, keepdims=True)
    exp_values = numpy.exp(shifted)
    return exp_values / numpy.sum(exp_values, axis=1, keepdims=True)


def decode_predictions(raw_output: Any, confidence_threshold: float) -> list[str]:
    numpy = require_module("numpy", "numpy")
    matrix = numpy.asarray(raw_output, dtype=numpy.float32)
    if matrix.ndim != 2 or matrix.shape[1] != len(COLOR_NAMES):
        raise RuntimeError(
            "classifier output must have shape [batch, 10] to match the color vocabulary"
        )
    probabilities = softmax_rows(matrix)
    named_probabilities = probabilities[:, : len(COLOR_NAMES) - 1]
    best_indices = numpy.argmax(named_probabilities, axis=1)
    best_confidences = named_probabilities[numpy.arange(len(best_indices)), best_indices]
    predictions: list[str] = []
    for best_index, confidence in zip(best_indices.tolist(), best_confidences.tolist()):
        if float(confidence) < confidence_threshold:
            predictions.append("unknown")
        else:
            predictions.append(COLOR_NAMES[int(best_index)])
    return predictions


def compute_latency_stats(samples_ms: list[float]) -> LatencyStats:
    numpy = require_module("numpy", "numpy")
    if not samples_ms:
        return LatencyStats(0.0, 0.0, 0.0)
    values = numpy.asarray(samples_ms, dtype=numpy.float64)
    return LatencyStats(
        p50_ms=float(numpy.percentile(values, 50)),
        p95_ms=float(numpy.percentile(values, 95)),
        p99_ms=float(numpy.percentile(values, 99)),
    )


def pair_confusion_rate(
    confusion_matrix: list[list[int]],
    left_color: str,
    right_color: str,
) -> float:
    left_index = COLOR_TO_INDEX[left_color]
    right_index = COLOR_TO_INDEX[right_color]
    pair_total = (
        sum(confusion_matrix[left_index]) + sum(confusion_matrix[right_index])
    )
    if pair_total == 0:
        return 0.0
    confused = (
        confusion_matrix[left_index][right_index]
        + confusion_matrix[right_index][left_index]
    )
    return confused / pair_total


def evaluate_candidate(
    records: list[CropRecord],
    candidate: AttributeCandidate,
    backend: ClassifierBackend,
    *,
    confidence_threshold: float,
    batch_size: int,
) -> AttributeMetrics:
    confusion_matrix = [[0 for _ in COLOR_NAMES] for _ in COLOR_NAMES]
    latency_samples_ms: list[float] = []
    inference_time_s = 0.0

    for start in range(0, len(records), batch_size):
        batch_records = records[start : start + batch_size]
        batch_tensor = load_batch_tensors(batch_records, candidate.input_size)
        started = time.perf_counter()
        raw_output = backend.infer_batch(batch_tensor)
        elapsed_s = time.perf_counter() - started
        inference_time_s += elapsed_s
        latency_samples_ms.append(elapsed_s * 1000.0)
        predictions = decode_predictions(raw_output, confidence_threshold)
        for record, prediction in zip(batch_records, predictions):
            true_index = COLOR_TO_INDEX[record.color_name]
            predicted_index = COLOR_TO_INDEX[prediction]
            confusion_matrix[true_index][predicted_index] += 1

    evaluated_crops = len(records)
    correct = sum(confusion_matrix[index][index] for index in range(len(COLOR_NAMES)))
    per_color_accuracy: dict[str, float] = {}
    for color_name, index in COLOR_TO_INDEX.items():
        row_total = sum(confusion_matrix[index])
        if row_total == 0:
            raise RuntimeError(
                f"evaluation manifest produced zero rows for required color {color_name!r}"
            )
        per_color_accuracy[color_name] = confusion_matrix[index][index] / row_total

    latency_stats = compute_latency_stats(latency_samples_ms)
    macro_per_color_accuracy = statistics.fmean(per_color_accuracy.values())
    unknown_predictions = sum(
        confusion_matrix[row_index][COLOR_TO_INDEX["unknown"]]
        for row_index in range(len(COLOR_NAMES))
    )
    throughput_fps = (
        evaluated_crops / inference_time_s if inference_time_s > 0.0 else 0.0
    )

    return AttributeMetrics(
        overall_accuracy=correct / evaluated_crops if evaluated_crops else 0.0,
        macro_per_color_accuracy=macro_per_color_accuracy,
        unknown_rate=unknown_predictions / evaluated_crops if evaluated_crops else 0.0,
        latency_p50_ms=latency_stats.p50_ms,
        latency_p95_ms=latency_stats.p95_ms,
        latency_p99_ms=latency_stats.p99_ms,
        throughput_fps=throughput_fps,
        evaluated_crops=evaluated_crops,
        batch_size=batch_size,
        per_color_accuracy=per_color_accuracy,
        confusion_matrix=confusion_matrix,
        confusion_black_blue=pair_confusion_rate(confusion_matrix, "black", "blue"),
        confusion_white_silver=pair_confusion_rate(
            confusion_matrix, "white", "silver"
        ),
        confusion_brown_orange=pair_confusion_rate(
            confusion_matrix, "brown", "orange"
        ),
    )


def build_summary_markdown(
    candidate: AttributeCandidate,
    backend_name: str,
    metadata: DatasetMetadata,
    metrics: AttributeMetrics,
    confidence_threshold: float,
) -> str:
    lines = [
        f"# Attribute Bake-Off Summary: {candidate.name}",
        "",
        f"- candidate: `{candidate.name}`",
        f"- backend: `{backend_name}`",
        f"- dataset manifest: `{metadata.manifest_path}`",
        f"- source project: `{metadata.source_project}`",
        f"- export timestamp: `{metadata.export_timestamp or 'unknown'}`",
        f"- evaluated crops: `{metrics.evaluated_crops}`",
        f"- batch size: `{metrics.batch_size}`",
        f"- confidence threshold: `{confidence_threshold:.2f}`",
        f"- overall accuracy: `{metrics.overall_accuracy:.4f}`",
        (
            "- macro per-color accuracy: "
            f"`{metrics.macro_per_color_accuracy:.4f}`"
        ),
        f"- unknown rate: `{metrics.unknown_rate:.4f}`",
        f"- latency p50 / p95 / p99 ms: "
        f"`{metrics.latency_p50_ms:.2f}` / "
        f"`{metrics.latency_p95_ms:.2f}` / "
        f"`{metrics.latency_p99_ms:.2f}`",
        f"- throughput crops/sec: `{metrics.throughput_fps:.2f}`",
        "",
        "## Per-Color Accuracy",
        "",
        "| Color | Accuracy |",
        "|-------|----------|",
    ]
    for color_name in COLOR_NAMES:
        lines.append(
            f"| {color_name} | {metrics.per_color_accuracy[color_name]:.4f} |"
        )
    return "\n".join(lines) + "\n"


def metrics_to_json_dict(metrics: AttributeMetrics) -> dict[str, Any]:
    return {
        "overall_accuracy": metrics.overall_accuracy,
        "macro_per_color_accuracy": metrics.macro_per_color_accuracy,
        "unknown_rate": metrics.unknown_rate,
        "latency_p50_ms": metrics.latency_p50_ms,
        "latency_p95_ms": metrics.latency_p95_ms,
        "latency_p99_ms": metrics.latency_p99_ms,
        "throughput_fps": metrics.throughput_fps,
        "evaluated_crops": metrics.evaluated_crops,
        "batch_size": metrics.batch_size,
        "per_color_accuracy": metrics.per_color_accuracy,
        "confusion_matrix": metrics.confusion_matrix,
        "confusion_black_blue": metrics.confusion_black_blue,
        "confusion_white_silver": metrics.confusion_white_silver,
        "confusion_brown_orange": metrics.confusion_brown_orange,
    }


def log_run_to_mlflow(
    *,
    args: argparse.Namespace,
    candidate: AttributeCandidate,
    backend_name: str,
    metadata: DatasetMetadata,
    metrics: AttributeMetrics,
    git_revision: str | None,
    git_dirty: bool | None,
) -> str:
    mlflow = require_module("mlflow", "mlflow")
    mlflow.set_tracking_uri(args.mlflow_uri)
    mlflow.set_experiment(args.mlflow_experiment)

    with tempfile.TemporaryDirectory(prefix="attribute-bakeoff-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        confusion_path = temp_dir / "confusion_matrix.json"
        per_color_path = temp_dir / "per_color_report.json"
        summary_path = temp_dir / "summary.md"

        confusion_path.write_text(
            json.dumps(
                {
                    "labels": list(COLOR_NAMES),
                    "matrix": metrics.confusion_matrix,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        per_color_path.write_text(
            json.dumps(
                {
                    "per_color_accuracy": metrics.per_color_accuracy,
                    "per_color_counts": metadata.per_color_counts,
                    "confusion_pairs": {
                        "black_blue": metrics.confusion_black_blue,
                        "white_silver": metrics.confusion_white_silver,
                        "brown_orange": metrics.confusion_brown_orange,
                    },
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        summary_path.write_text(
            build_summary_markdown(
                candidate,
                backend_name,
                metadata,
                metrics,
                args.confidence_threshold,
            ),
            encoding="utf-8",
        )

        with mlflow.start_run(run_name=f"attribute-{candidate.name}") as run:
            mlflow.set_tags(
                {
                    "bakeoff.phase": "attribute",
                    "bakeoff.candidate": candidate.name,
                    "bakeoff.safe_default": str(candidate.is_safe_default).lower(),
                    "bakeoff.protocol_version": "1.0.0",
                }
            )
            params = {
                "candidate_name": candidate.name,
                "onnx_path": str(candidate.onnx_path),
                "triton_model_name": candidate.triton_model_name,
                "input_name": candidate.input_name,
                "output_name": candidate.output_name,
                "input_size": candidate.input_size,
                "confidence_threshold": args.confidence_threshold,
                "dataset_manifest": str(metadata.manifest_path),
                "source_project": metadata.source_project,
                "backend": backend_name,
                "batch_size": args.batch_size,
            }
            if metadata.export_timestamp is not None:
                params["dataset_export_timestamp"] = metadata.export_timestamp
            if args.triton_url.strip():
                params["triton_url"] = args.triton_url.strip()
            if git_revision is not None:
                params["git_revision"] = git_revision
            if git_dirty is not None:
                params["git_dirty"] = str(git_dirty).lower()
            mlflow.log_params(params)
            mlflow.log_metrics(
                {
                    "overall_accuracy": metrics.overall_accuracy,
                    "macro_per_color_accuracy": metrics.macro_per_color_accuracy,
                    "unknown_rate": metrics.unknown_rate,
                    "latency_p50_ms": metrics.latency_p50_ms,
                    "latency_p95_ms": metrics.latency_p95_ms,
                    "latency_p99_ms": metrics.latency_p99_ms,
                    "throughput_fps": metrics.throughput_fps,
                    "confusion_black_blue": metrics.confusion_black_blue,
                    "confusion_white_silver": metrics.confusion_white_silver,
                    "confusion_brown_orange": metrics.confusion_brown_orange,
                    "evaluated_crops": float(metrics.evaluated_crops),
                }
            )
            for color_name, value in metrics.per_color_accuracy.items():
                mlflow.log_metric(f"attr_accuracy_{color_name}", value)
            mlflow.log_artifact(str(confusion_path))
            mlflow.log_artifact(str(per_color_path))
            mlflow.log_artifact(str(summary_path))
            return run.info.run_id


def run_evaluation(args: argparse.Namespace) -> tuple[str, AttributeMetrics]:
    if args.batch_size <= 0:
        raise RuntimeError("--batch-size must be positive")
    candidate = resolve_candidate(args)
    records, metadata = load_manifest(args.manifest)
    backend_name, backend = select_backend(candidate, args.triton_url)
    metrics = evaluate_candidate(
        records,
        candidate,
        backend,
        confidence_threshold=args.confidence_threshold,
        batch_size=args.batch_size,
    )
    git_revision, git_dirty = detect_git_state()
    run_id = log_run_to_mlflow(
        args=args,
        candidate=candidate,
        backend_name=backend_name,
        metadata=metadata,
        metrics=metrics,
        git_revision=git_revision,
        git_dirty=git_dirty,
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    local_summary_path = args.output_dir / f"{candidate.name}_summary.json"
    local_summary_path.write_text(
        json.dumps(
            {
                "candidate": candidate.name,
                "backend": backend_name,
                "dataset": {
                    "manifest_path": str(metadata.manifest_path),
                    "export_timestamp": metadata.export_timestamp,
                    "source_project": metadata.source_project,
                    "total_crops": metadata.total_crops,
                    "per_color_counts": metadata.per_color_counts,
                },
                "metrics": metrics_to_json_dict(metrics),
                "mlflow_run_id": run_id,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "candidate": candidate.name,
                "backend": backend_name,
                "overall_accuracy": round(metrics.overall_accuracy, 6),
                "macro_per_color_accuracy": round(
                    metrics.macro_per_color_accuracy, 6
                ),
                "unknown_rate": round(metrics.unknown_rate, 6),
                "latency_p95_ms": round(metrics.latency_p95_ms, 3),
                "throughput_fps": round(metrics.throughput_fps, 3),
                "mlflow_run_id": run_id,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return run_id, metrics


def main() -> None:
    run_evaluation(parse_args())


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        raise SystemExit(str(exc)) from exc
