"""NATS JetStream publisher for FrameRef protobuf messages.

Publishes serialized ``FrameRef`` messages to per-site NATS subjects:

- Live traffic:   ``frames.live.<site_id>.<camera_id>``
- Replay traffic: ``frames.replay.<site_id>.<camera_id>``

The subject hierarchy matches the ACL matrix in ``docs/security-design.md``.
mTLS is used when certificate paths are provided (CN = ``edge-site-<site_id>``).
"""

from __future__ import annotations

import logging
import os
import ssl
import sys
import time
from datetime import datetime, timezone

import nats
from nats.aio.client import Client as NATS

from metrics import NATS_LATENCY

logger = logging.getLogger(__name__)

# Allow proto_gen imports at runtime (generated by gen_proto.sh).
_proto_gen = os.path.join(os.path.dirname(os.path.abspath(__file__)), "proto_gen")
if _proto_gen not in sys.path:
    sys.path.insert(0, _proto_gen)


# ------------------------------------------------------------------
# Protobuf serialisation
# ------------------------------------------------------------------


def serialize_frame_ref(
    *,
    frame_id: str,
    camera_id: str,
    frame_uri: str,
    frame_sequence: int,
    source_capture_ts: float,
    edge_receive_ts: float,
    width_px: int,
    height_px: int,
    codec: str = "jpeg",
    clock_quality: int = 3,  # CLOCK_QUALITY_ESTIMATED
) -> bytes:
    """Build a ``FrameRef`` protobuf and return its wire-format bytes.

    ``core_ingest_ts`` is intentionally left unset — it is stamped by the
    ingress bridge when the message first enters the core domain
    (see ``docs/time-sync-policy.md``).
    """
    from google.protobuf.timestamp_pb2 import Timestamp  # noqa: PLC0415

    from vidanalytics.v1.common import common_pb2  # noqa: PLC0415
    from vidanalytics.v1.frame import frame_pb2  # noqa: PLC0415

    def _ts(epoch: float) -> Timestamp:
        t = Timestamp()
        t.FromDatetime(datetime.fromtimestamp(epoch, tz=timezone.utc))
        return t

    ts = common_pb2.VideoTimestamp(
        source_capture_ts=_ts(source_capture_ts),
        edge_receive_ts=_ts(edge_receive_ts),
        # core_ingest_ts left unset — stamped by ingress bridge
        clock_quality=clock_quality,
    )
    ref = frame_pb2.FrameRef(
        frame_id=frame_id,
        camera_id=camera_id,
        frame_uri=frame_uri,
        frame_sequence=frame_sequence,
        timestamps=ts,
        width_px=width_px,
        height_px=height_px,
        codec=codec,
    )
    return ref.SerializeToString()


# ------------------------------------------------------------------
# TLS helper
# ------------------------------------------------------------------


def _make_tls_context(
    cert_file: str, key_file: str, ca_file: str
) -> ssl.SSLContext:
    ctx = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH)
    ctx.load_verify_locations(ca_file)
    ctx.load_cert_chain(cert_file, key_file)
    return ctx


# ------------------------------------------------------------------
# Publisher
# ------------------------------------------------------------------


class NatsPublisher:
    """Publishes serialized protobuf payloads to NATS JetStream."""

    def __init__(
        self,
        url: str,
        site_id: str,
        *,
        cert_file: str | None = None,
        key_file: str | None = None,
        ca_file: str | None = None,
    ) -> None:
        self._url = url
        self._site_id = site_id
        self._cert_file = cert_file
        self._key_file = key_file
        self._ca_file = ca_file
        self._nc: NATS | None = None
        self._js = None  # JetStreamContext

    async def connect(self) -> None:
        """Connect to NATS (with optional mTLS) and obtain a JetStream handle."""
        tls_ctx = None
        if self._cert_file and self._key_file and self._ca_file:
            tls_ctx = _make_tls_context(
                self._cert_file, self._key_file, self._ca_file
            )
        self._nc = await nats.connect(
            self._url,
            tls=tls_ctx,
            max_reconnect_attempts=-1,
            reconnect_time_wait=2,
            disconnected_cb=self._on_disconnect,
            reconnected_cb=self._on_reconnect,
            error_cb=self._on_error,
        )
        self._js = self._nc.jetstream()
        logger.info("Connected to NATS at %s", self._url)

    async def publish(
        self, subject: str, payload: bytes, *, camera_id: str = ""
    ) -> bool:
        """Publish *payload* to *subject*. Returns ``True`` on success."""
        if self._js is None:
            return False
        t0 = time.monotonic()
        try:
            await self._js.publish(subject, payload)
            elapsed_ms = (time.monotonic() - t0) * 1000
            NATS_LATENCY.labels(camera_id=camera_id).observe(elapsed_ms)
            return True
        except Exception:
            logger.warning("NATS publish failed on %s", subject, exc_info=True)
            return False

    def live_subject(self, camera_id: str) -> str:
        """Return the live-traffic NATS subject for a camera."""
        return f"frames.live.{self._site_id}.{camera_id}"

    def replay_subject(self, camera_id: str) -> str:
        """Return the replay-traffic NATS subject for a camera."""
        return f"frames.replay.{self._site_id}.{camera_id}"

    @property
    def is_connected(self) -> bool:
        return self._nc is not None and self._nc.is_connected

    async def close(self) -> None:
        if self._nc is not None:
            await self._nc.close()
            logger.info("NATS connection closed")

    # Callbacks --------------------------------------------------------

    async def _on_disconnect(self) -> None:
        logger.warning("NATS disconnected")

    async def _on_reconnect(self) -> None:
        logger.info("NATS reconnected")

    async def _on_error(self, e: Exception) -> None:
        logger.error("NATS error: %s", e)
