[mypy]
strict = true

[mypy-asyncpg.*]
ignore_missing_imports = true

[mypy-confluent_kafka.*]
ignore_missing_imports = true

[mypy-minio.*]
ignore_missing_imports = true

[mypy-yaml.*]
ignore_missing_imports = true

[mypy-vidanalytics.*]
ignore_missing_imports = true

[mypy-prometheus_client.*]
ignore_missing_imports = true

[mypy-PIL.*]
ignore_missing_imports = true
