[mypy]
strict = true

[mypy-asyncpg.*]
ignore_missing_imports = true

[mypy-faiss.*]
ignore_missing_imports = true

[mypy-confluent_kafka.*]
ignore_missing_imports = true

[mypy-scipy.*]
ignore_missing_imports = true

[mypy-yaml.*]
ignore_missing_imports = true

[mypy-vidanalytics.*]
ignore_missing_imports = true

[mypy-topology_models.*]
ignore_missing_imports = true

[mypy-prometheus_client.*]
ignore_missing_imports = true

[mypy-pydantic_settings.*]
ignore_missing_imports = true

[mypy-pydantic.*]
ignore_missing_imports = true

[mypy-minio.*]
ignore_missing_imports = true
