streams:
  cam-1: "ffmpeg:rtsp://admin:Qwerty12@192.168.1.67:554/Streaming/Channels/101#video=h264"
  cam-2: "ffmpeg:rtsp://admin:Qwerty12@192.168.1.64:554/Streaming/Channels/101#video=h264"

api:
  listen: ":1984"
  origin: "*"

rtsp:
  listen: ":8554"
